# CONFIGURATION FILE FOR DEMERIT_RB or DEMERIT_PY

grade_dir: "/usr/cs/2016/imcgaunn/submit/spiral"
demerit_dir: "~/demerit_rb"

assign_name: "spiral"
gen_makefile: true

run_programs: true
stdin: "5 16"
argv: ""
